remove cmsis-dsp and cmsis-nn
zephyrproject-rtos/cmsis pull request #21
Opened 2023-05-02 18:05 UTC by XenuIsWatching

As CMSIS-DSP and CMSIS-NN are moving to their own repository, this removes them from the cmsis repo

2023-05-12 11:03 UTC, stephanosio requested changes
The changes look ok, but please add some details regarding why these are being removed in the commit message.

2023-05-18 00:08 UTC, XenuIsWatching commented
> The changes look ok, but please add some details regarding why these are being removed in the commit message.

Ah... yeah, I'm quite lazy with commit messages, I went and corrected all the other's before pushing... but apperently, I forgot this one

2023-05-18 06:48 UTC, stephanosio approved these changes

2023-05-18 06:48 UTC, stephanosio approved these changes

2023-08-27 05:40 UTC, XenuIsWatching commented
rebasing

2023-09-21 18:03 UTC, yperess approved these changes

2023-09-22 12:03 UTC, merged