Core-r7: Make GIC and TIM configurable
zephyrproject-rtos/cmsis pull request #8
Opened 2020-12-07 15:18 UTC by julien-massot

This is a preliminary change in order to introduce Cortex R7 support in Zephyr.

When including core_cr7.h from zehyr, compiler complains about undefined GIC_BASE and TIMER_BASE,
but GIC already have a driver in zephyr which just works with Cortex-R7 and a different timer than the
private timer may be used.

Give the choice the the soc definition to enable or disable GIC, and Timer implementation of the cmsis package.

2020-12-07 15:36 UTC, galak commented
Looks reasonable.

2020-12-07 15:36 UTC, galak approved these changes

2020-12-07 15:37 UTC, galak commented
Can you make this change to all the Core_R/Include/core_cr*.h files

2020-12-07 15:38 UTC, galak submitted a review, later dismissed
Please make this change to all the core_cr*.h files

2020-12-07 15:39 UTC, carlescufi commented
Agreed, this should apply to all Cortex-R cores

2020-12-07 15:40 UTC, julien-massot commented
> Please make this change to all the core_cr*.h files

sure will do! Thanks for this super quick review.

2020-12-07 15:43 UTC, julien-massot commented
BTW, only Cortex R7 and R8 have GIC and private timer so will only change these two files.

2020-12-07 15:45 UTC, galak commented
> BTW, only Cortex R7 and R8 have GIC and private timer so will only change these two files.

What about cortex-r52?

2020-12-07 15:50 UTC, julien-massot commented
> What about cortex-r52?
Nice catch, I missed that one. thanks.

2020-12-11 11:50 UTC, stephanosio requested changes
Since we are making `__GIC_PRESENT` and `__TIM_PRESENT` configurable in these headers, we should make them configurable in `core_r4.h` and `core_r5.h` as well for the sake of consistency.

As a matter of fact, Cortex-R5 can be configured to use GIC, as was done in ZynqMP (Cortex-R5 + GICv1).

2020-12-16 14:49 UTC, julien-massot commented
Hi @stephanosio  Thanks for the review.
I did change the commit to modify all members of the Cortex R family the same way.
Regards,
julien

2020-12-17 11:04 UTC, stephanosio approved these changes

2021-01-13 08:03 UTC, julien-massot commented
Hi @galak @stephanosio does it's possible to merge this PR ? thanks.

2021-01-14 14:00 UTC, galak approved these changes

2021-01-14 14:01 UTC, merged

2021-01-14 14:01 UTC, galak commented
> Hi @galak @stephanosio does it's possible to merge this PR ? thanks.

merged

2021-01-14 14:41 UTC, julien-massot commented
> > Hi @galak @stephanosio does it's possible to merge this PR ? thanks.
> 
> merged

Thanks,
Does I need to send a PR for updating the manifest then ?

2021-01-14 14:43 UTC, galak commented
Yes.