DSP: Support compiling on native posix
zephyrproject-rtos/cmsis pull request #9
Opened 2021-01-13 17:48 UTC by shlomow

This commit adds support to compile cmsis-dsp
library on the host. The only definition that is
needed is `__GNUC_PYTHON__`. This makes the library
support compilation for native.

Signed-off-by: Shlomi Vaknin <shlomi.39sd@gmail.com>

2021-01-14 13:49 UTC, galak requested changes
Can you update commit message to explain why __GNUC_PYTHON__ needs to be set at all for this case as well.

2021-01-14 13:50 UTC, galak commented on CMSIS/DSP/CMakeLists.txt
> +zephyr_compile_definitions_ifdef(CONFIG_BOARD_NATIVE_POSIX __GNUC_PYTHON__)
I would have this depend on something like CONFIG_ARCH_POSIX instead.

2021-01-19 21:15 UTC, shlomow commented
@galak is this ok? I would like to merge this feature before v2.5.0 as it quite simple and useful for me

2021-01-20 13:46 UTC, galak approved these changes

2021-01-20 13:46 UTC, merged

2021-01-20 13:47 UTC, galak commented
> @galak is this ok? I would like to merge this feature before v2.5.0 as it quite simple and useful for me

Looks good, thanks.